apiVersion: v1
kind: ConfigMap
metadata:
  name: pts-config
  namespace: default
data:
  phoronix-test-suite.xml: |
    <?xml version="1.0"?>
    <!--Phoronix Test Suite v10.2.1-->
    <PhoronixTestSuite>
      <Options>
        <OpenBenchmarking>
          <AnonymousUsageReporting>TRUE</AnonymousUsageReporting>
          <IndexCacheTTL>3</IndexCacheTTL>
          <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>
          <AllowResultUploadsToOpenBenchmarking>TRUE</AllowResultUploadsToOpenBenchmarking>
        </OpenBenchmarking>
        <General>
          <DefaultBrowser></DefaultBrowser>
          <UsePhodeviCache>TRUE</UsePhodeviCache>
          <DefaultDisplayMode>DEFAULT</DefaultDisplayMode>
          <PhoromaticServers></PhoromaticServers>
          <FullOutput>FALSE</FullOutput>
          <ColoredConsole>AUTO</ColoredConsole>
        </General>
        <Modules>
          <AutoLoadModules>toggle_screensaver, update_checker, perf_tips, ob_auto_compare, load_dynamic_result_viewer</AutoLoadModules>
        </Modules>
        <Installation>
          <RemoveDownloadFiles>FALSE</RemoveDownloadFiles>
          <SearchMediaForCache>TRUE</SearchMediaForCache>
          <SymLinkFilesFromCache>FALSE</SymLinkFilesFromCache>
          <PromptForDownloadMirror>FALSE</PromptForDownloadMirror>
          <EnvironmentDirectory>~/.phoronix-test-suite/installed-tests/</EnvironmentDirectory>
          <CacheDirectory>~/.phoronix-test-suite/download-cache/</CacheDirectory>
        </Installation>
        <Testing>
          <SaveSystemLogs>TRUE</SaveSystemLogs>
          <SaveInstallationLogs>TRUE</SaveInstallationLogs>
          <SaveTestLogs>TRUE</SaveTestLogs>
          <RemoveTestInstallOnCompletion></RemoveTestInstallOnCompletion>
          <ResultsDirectory>~/.phoronix-test-suite/test-results/</ResultsDirectory>
          <AlwaysUploadResultsToOpenBenchmarking>FALSE</AlwaysUploadResultsToOpenBenchmarking>
          <AutoSortRunQueue>TRUE</AutoSortRunQueue>
          <ShowPostRunStatistics>TRUE</ShowPostRunStatistics>
        </Testing>
        <TestResultValidation>
          <DynamicRunCount>TRUE</DynamicRunCount>
          <LimitDynamicToTestLength>20</LimitDynamicToTestLength>
          <StandardDeviationThreshold>2.5</StandardDeviationThreshold>
          <ExportResultsTo></ExportResultsTo>
          <MinimalTestTime>2</MinimalTestTime>
          <DropNoisyResults>FALSE</DropNoisyResults>
        </TestResultValidation>
        <ResultViewer>
          <WebPort>RANDOM</WebPort>
          <LimitAccessToLocalHost>TRUE</LimitAccessToLocalHost>
          <AccessKey></AccessKey>
          <AllowSavingResultChanges>TRUE</AllowSavingResultChanges>
          <AllowDeletingResults>TRUE</AllowDeletingResults>
        </ResultViewer>
        <BatchMode>
          <SaveResults>TRUE</SaveResults>
          <OpenBrowser>FALSE</OpenBrowser>
          <UploadResults>TRUE</UploadResults>
          <PromptForTestIdentifier>FALSE</PromptForTestIdentifier>
          <PromptForTestDescription>FALSE</PromptForTestDescription>
          <PromptSaveName>FALSE</PromptSaveName>
          <RunAllTestCombinations>TRUE</RunAllTestCombinations>
          <Configured>TRUE</Configured>
        </BatchMode>
        <Networking>
          <NoInternetCommunication>FALSE</NoInternetCommunication>
          <NoNetworkCommunication>FALSE</NoNetworkCommunication>
          <Timeout>20</Timeout>
          <ProxyAddress></ProxyAddress>
          <ProxyPort></ProxyPort>
          <ProxyUser></ProxyUser>
          <ProxyPassword></ProxyPassword>
        </Networking>
        <Server>
          <RemoteAccessPort>RANDOM</RemoteAccessPort>
          <Password></Password>
          <WebSocketPort>RANDOM</WebSocketPort>
          <AdvertiseServiceZeroConf>TRUE</AdvertiseServiceZeroConf>
          <AdvertiseServiceOpenBenchmarkRelay>TRUE</AdvertiseServiceOpenBenchmarkRelay>
          <PhoromaticStorage>~/.phoronix-test-suite/phoromatic/</PhoromaticStorage>
        </Server>
      </Options>
    </PhoronixTestSuite>

---
apiVersion: batch/v1
kind: Job
metadata:
  name: bench-wyse
  namespace: default
spec:
  template:
    metadata:
      labels:
        job-name: bench-wyse
        test: cpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: model
                operator: In
                values:
                - wyse5070
      containers:
      - command:
        - /bin/bash
        - -c
        - apt-get update && apt-get install -y build-essential && /phoronix-test-suite/phoronix-test-suite batch-benchmark pts/cpu
        image: phoronix/pts
        name: bench
        resources:
          limits:
            cpu: 2
            memory: "3Gi"
          requests:
            cpu: 2
            memory: "3Gi"
        volumeMounts:
        - name: bench-config
          mountPath: /etc/phoronix-test-suite.xml
          subPath: phoronix-test-suite.xml
      restartPolicy: Never
      volumes:
      - name: bench-config
        configMap:
          name: pts-config
