apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  namespace: backup
  name: backups
spec:
  bucketName: hostbackup
  storageClassName: rook-object-store
  additionalConfig:
    maxObjects: "100000"
    maxSize: "800G"
