apiVersion: v1
kind: Namespace
metadata:
  name: backups
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  namespace: backups
  name: backup
spec:
  bucketName: hostbackup
  storageClassName: rook-object-store
  additionalConfig:
    maxObjects: "100000"
    maxSize: "800G"
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: laptop-token
  namespace: backups
spec:
  store: objects
  displayName: laptop-token
