---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 30
               "memory": 20
               "pods": 10
             targetThresholds:
               "cpu" : 80
               "memory": 65
               "pods": 30
      "RemovePodsViolatingTopologySpreadConstraint":
        enabled: true
      "PodLifeTime":
        enabled: true
        params:
          podLifeTime:
            maxPodLifeTimeSeconds: 4320000
            namespaces:
              include:
              - knative-serving
              - flux-system
              - contour-default
              - contour-internal
            podStatusPhases:
            - "Running"
            - "Pending"