# using https://github.com/twuni/docker-registry.helm
persistence:
  enabled: true
  size: 200G
  storageClass: rook-default-replicated
namespace: registry
ingress:
  enabled: true
  className: contour-external
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-ca
  hosts:
  - registry.lab.eandersons.net
  tls:
  - hosts:
    - registry.lab.eandersons.net
    secretName: registry-cert

# To use this with Docker:
#   kubectl view secret -n cert-manager ca-secret ca.crt > ~/.docker/certs.d/$HOSTNAME/ca.crt
#   (also works on Windows)
#
# To use this with `ko` (only works on Linux):
#   export SSL_CERT_FILE=~/.docker/certs.d/$HOSTNAME/ca.crt