apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  namespace: wordpress
  name: wp-bucket
spec:
  bucketName: wordpress-store
  storageClassName: rook-object-store
  additionalConfig:
    maxObjects: "100000"
    maxSize: "5G"
