apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: evan.k.anderson@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: eandersons-net
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-account
            key: key.json
      selector:
        dnsZones:
        - 'off-by-one.dev'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: evan.k.anderson@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: eandersons-net
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-account
            key: key.json
      selector:
        dnsZones:
        - 'off-by-one.dev'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-root
  namespace: cert-manager
spec:
  isCA: true
  commonName: selfsigned-root
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-ca
spec:
  ca:
    secretName: ca-secret
