apiVersion: v1
kind: Namespace
metadata:
  name: net-update
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: set-dns
  namespace: net-update
spec:
  schedule: "* * * * *"  # Every minute
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: get-external-ip
            image: us-west1-docker.pkg.dev/k8s-foo/evana-public/netshoot@sha256:2cb1e0640419ac7c0df9fc9130f38b677d7649403a20aeaabcbc56ba69a342c1
            command: ["/bin/bash", "-c"]
            args:
            # The actual MIB contains the IP address, so we need to extract it from the MIB _name_ \o/
            # pppoe if is 38, 
            - "snmpgetnext -v 2c -c $(COMMUNITY) 192.168.0.1 IP-MIB::ipAddressPrefixOrigin.40.ipv4 | grep -o '\".*\"' | sed 's/\"//g' > /ipaddr/external"
            env:
            - name: COMMUNITY
              valueFrom:
                secretKeyRef:
                  key: community
                  name: snmp
            volumeMounts:
            - name: shared
              mountPath: /ipaddr
          containers:
          - name: set-dns
            # Was :slim target
            image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:376d55f6a227676d41a141713046893cab839b7126990fedbe5f86a6a4a06e25
            command: ["/bin/bash", "-c"]
            args:
            - "gcloud auth activate-service-account --key-file /google/sa.json && gcloud --project $(cat /google/project) dns record-sets update --zone $(cat /google/zone) off-by-one.dev. --type A --rrdatas=$(cat /ipaddr/external)"
            volumeMounts:
            - name: shared
              mountPath: /ipaddr
            - name: google-creds
              mountPath: /google
          enableServiceLinks: false
          volumes:
          - name: shared
            emptyDir: {}
          - name: google-creds
            secret:
              secretName: dns-google-sa
              defaultMode: 444
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          restartPolicy: Never
