apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: objects
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef: rook-ceph.microkn.off-by-one.dev
    port: 80
    securePort: 443
    instances: 1
  healthCheck:
    bucket:
      interval: 60s
