apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-db
  namespace: wordpress
spec:
  replicas: 1
  secretName: mysql-root
  podSpec:
    metricsExporterResources: {}
    mysqlOperatorSidecarResources: {}
    resources:
      requests:
        memory: 400M
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "100Gi"
