apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: off-by-one
  namespace: wordpress
spec:
  secretName: staging-site
  issuerRef:
    # The issuer created previously
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - off-by-one.dev
  - '*.off-by-one.dev'

